[package]
name = "dsmr-rs"
version = "0.6.1"
authors = ["Maarten Mulders <mthmulders@noreply.github.com>"]
edition = "2018"
description = "A utility to ship 'smart meter' readings over HTTP"
license = "MIT License"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
maintainer = "Maarten Mulders"
maintainer-scripts = "debian/"
copyright = "2021 - 2023 Maarten Mulders"

[package.metadata.deb.systemd-units]


[dependencies]
config = "0.14.0"
log = "0.4.21"
simplelog = "0.12.2"

[dependencies.serialport]
version = "4.3.0"
default-features = false

[dependencies.reqwest]
version = "0.12.4"
features = [ "blocking" ]

[dependencies.openssl]
version = "0.10.64"
# Build OpenSSL as part of building this crate
features = [ "vendored" ]

# Ensure we select OpenSSL 3.x
[dependencies.openssl-src]
version = "300.2.3+3.1.1"
