[package]
name = "dsmr-rs"
version = "0.1.0"
authors = ["Maarten Mulders <mthmulders@noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
log = "0.4.14"
simplelog = "0.11.2"

[dependencies.serialport]
version = "4.0.1"
default-features = false

[dependencies.reqwest]
version = "0.11.11"
features = [ "blocking" ]
