[package]
name = "dsmr-rs"
version = "0.1.0"
authors = ["Maarten Mulders <mthmulders@noreply.github.com>"]
edition = "2018"
description = "A utility to ship 'smart meter' readings over HTTP"
license = "MIT License"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
maintainer = "Maarten Mulders"
copyright = "2021 - 2023 Maarten Mulders"

[dependencies]
config = "0.13.3"
log = "0.4.19"
simplelog = "0.12.1"

[dependencies.serialport]
version = "4.2.1"
default-features = false

[dependencies.reqwest]
version = "0.11.9"
features = [ "blocking" ]

[dependencies.openssl]
version = "0.10.55"
# Build OpenSSL as part of building this crate
features = [ "vendored" ]

# Ensure we select OpenSSL 3.x
[dependencies.openssl-src]
version = "300.1.2+3.1.1"
