name: Security audit

on:
  schedule:
    - cron: '14 3 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.5.3

      - name: Install build requirements
        run: |
          sudo apt update -y
          sudo apt install -y libssl-dev

      - name: Run cargo audit
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}