name: Build Debian packages for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    # Consider creating a matrix to also include armv7-unknown-linux-musleabihf

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.5.3

      - name: Preserve built binaries
        uses: swatinem/rust-cache@v2.6.0

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1.15.0
        with:
          target: arm-unknown-linux-musleabihf

      - name: Perform build
        run: |
          cargo build --target arm-unknown-linux-musleabihf --release --features ""

  package:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Re-use pre-built binaries
        uses: swatinem/rust-cache@v2.6.0

      - name: Display structure of downloaded files
        run: find target/

      - name: Prepare packaging
        run: |
          sudo apt update -y
          sudo apt install -y dpkg dpkg-dev liblzma-dev libssl-dev
          cargo install cargo-deb

      - name: Create Debian package
        run: |
          cargo deb --target arm-unknown-linux-musleabihf --strip

      - name: Display structure of package directory 
        run: find target/debian/
      
      - name: Upload Debian packages
        uses: actions/upload-artifact@v3.1.2
        if: github.ref == 'refs/heads/main'
        with:
          name: binaries
          path: target/debian/
