name: Build for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download ARM Toolchain
        run: |
          pushd /tmp
          wget -q "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz?revision=d0b90559-3960-4e4b-9297-7ddbc3e52783&la=en&hash=985078B758BC782BC338DB947347107FBCF8EF6B" \
            -O gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz
          tar xf gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz

      - name: Install cross-build dependencies
        run: |
          sudo apt update -y
          sudo apt install -y gcc-arm-linux-gnueabihf

      - name: Install armhf build dependencies
        uses: ryankurte/action-apt@v0.3.0
        with:
          arch: armhf
          packages: "libssl-dev:armhf libudev-dev:armhf"

      - name: Perform build
        run: |
          ./cross-compile-armv7.sh
        env:
          ARMHF_TOOLCHAIN_PATH: "/tmp/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/"
      
      - name: Upload application
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: dsmr-rs
          path: target/armv7-unknown-linux-gnueabihf/release/dsmr-rs
