name: Build for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.5.3

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1.15.0
        with:
          target: arm-unknown-linux-musleabihf

      - name: Perform build
        run: |
          cargo build --target arm-unknown-linux-musleabihf --release --features ""

      - name: Verify
        run: |
          file target/arm-unknown-linux-musleabihf/release/dsmr-rs
      
      - name: Upload application
        uses: actions/upload-artifact@v3.1.2
        if: github.ref == 'refs/heads/main'
        with:
          name: dsmr-rs
          path: target/arm-unknown-linux-musleabihf/release/dsmr-rs
