name: Security audit

on:
  schedule:
    - cron: '14 3 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      checks: write  # for rustsec/audit-check to create check
      contents: read  # for actions/checkout to fetch code
      issues: write  # for rustsec/audit-check to create issues
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.6

      - name: Install build requirements
        run: |
          sudo apt update -y
          sudo apt install -y libssl-dev

      - name: Audit Check
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}